### ISSUE TITLE
Not seeing the pipe cmd in the cypress log

### ISSUE THREAD

**Issue by tnrich** [NicholasBoll/cypress-pipe#13]
Hey there, 

I'm trying to run your default example: 
![image](https://user-images.githubusercontent.com/2730609/56063621-a631d400-5d24-11e9-9333-ba8a5fc819c0.png)

however, with pipe installed in `support/index.js` I'm not seeing the actual custom `PIPE` command being logged. Here's what I see: 
![image](https://user-images.githubusercontent.com/2730609/56063597-90bcaa00-5d24-11e9-9fcf-ff21db7bd7e9.png)

Any thoughts on why this is?

**Comment by NicholasBoll** [comment]
Oh no! You're totally right! I upgraded to Cypress@3.2.0 and the log stopped showing up! I'll work on that. I was still on Cypress 3.1.x and didn't notice. Thanks for pointing this out.

**Comment by NicholasBoll** [comment]
Nevermind, I figured it out. I accidentally removed the `log: true` default option in #9. I'll open a PR.

**Comment by NicholasBoll** [comment]
Released as 1.3.6
