### ISSUE TITLE
Trying to use loggable but it doesn't seem to be release in cypress-pipe@1.6.0

### ISSUE THREAD

**Issue by westhomas** [NicholasBoll/cypress-pipe#19]
Can't seem to reconcile the latest README's `loggable` feature with what's available in npm's 1.6.0.

```
$ npm list | grep pipe
├── cypress-pipe@1.6.0
```

Trying to import:
```
import { loggable } from 'cypress-pipe'
```

Cypress throws and error:
```
Uncaught TypeError: (0 , _cypressPipe.loggable) is not a function
```

**Comment by NicholasBoll** [comment]
Oh, no! Thanks for bringing this up. I'll check it out

**Comment by NicholasBoll** [comment]
You're right! I forgot to add the loggable files to the `package.json` file. I publish 1.6.1 to fix.

**Comment by westhomas** [comment]
Seems to work now, but I have to import it like this: 

```
import { loggable } from 'cypress-pipe/loggable'
```

**Comment by NicholasBoll** [comment]
Doh! I've added `{ loggable }` to both the runtime export and the Typescript file. Released as 1.6.2

**Comment by NicholasBoll** [comment]
Tests now cover this export. Sorry about that! https://github.com/NicholasBoll/cypress-pipe/commit/fc6fe92fb07bd8dfa5b1a75de494efbed45763e9

**Comment by westhomas** [comment]
Old import works now. Thanks!
