### ISSUE TITLE
TypeScript error

### ISSUE THREAD

**Issue by patrickberkeley** [NicholasBoll/cypress-pipe#25]
Thanks for making this plugin! It is functioning correctly. However I am getting a TS error when chaining `pipe` onto `cy.wrap`. Here's a screenshot:

![](https://screen-caps.s3.amazonaws.com/atYP3e781mz1FoGnmVEczqqQZ7ITemcjIL85ScSYZjDC3RwNQcykrre3XbTj94vgiTnt5kWhmNagtHOXowoyyshlxGOrM0oouqPc.png)

And the offending code:

```ts
          cy.wrap(counts)
            .pipe(getRoundStateChangeCallCount)
            .should('equal', 1);
```

I have TS as a dependency (not dev dependency), and the following is in `tsconfig.json`:

```json
{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "cypress-file-upload"]
  },
  "include": [
    "**/*.ts"
  ]
}
```

Any ideas on how to get the error to go away?

**Comment by NicholasBoll** [comment]
Typescript can be difficult with global types like Cypress. If your `support` file is a Typescript file and it is included via the `tsconfig.json` `includes` property, it should include the `pipe` types. If the support file is a JS file, you'll need to add `"cypress-pipe"` to your `types` property in the tsconfig file.

**Comment by patrickberkeley** [comment]
> `support` file is a Typescript file

🏆 Changing `support/index.js` to `.ts` fixed it. Thanks @NicholasBoll !
